version: '3.11'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "6000:6000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: password-manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
